const tutorsInfo= [
  {
      id: 1, 
      name:"Avinash Jha", 
      info:'UI/UX Designer', 
      course:'19 courses', 
      rating:'4.7 (689459)',
      pic:"https://img.freepik.com/free-photo/emotions-people-concept-headshot-serious-looking-handsome-man-with-beard-looking-confident-determined_1258-26730.jpg", 
    },  
    {
      id: 2, 
      name:"Avik kumar Das", 
      info:'Full Stack Developer', 
      course:'22 courses', 
      rating:'4.7 (349100)',
      pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8uTzI63eCsEQfgD4yFlzFPOtYQAOxKwT8eA&s", 
    }, {
      id: 3, 
      name:"Anuska Mishra", 
      info:'Backend Developer', 
      course:'20 courses', 
      rating:'4.7 (781002)',
      pic:"https://th.bing.com/th/id/OIP.p-PiFX9nE-Ug0of60Rc8VAHaHa?w=2048&h=2048&rs=1&pid=ImgDetMain", 
    }, {
      id: 4 , 
      name:"Sadhan Das", 
      info:'UI/UX Designer', 
      course:'15 courses', 
      rating:'4.7 (667790)',
      pic:"https://media.istockphoto.com/id/1025855448/photo/stylish-bearded-man-with-trendy-haircut-smiling-to-camera-having-pleased-expression-and.jpg?b=1&s=612x612&w=0&k=20&c=lGCt-Wanp6GOas1xJaQKF6pHkfZQp8b2MRoCl_Ogmfk=", 
    }, {
      id: 5, 
      name:"Ankita Samanta", 
      info:'Full Stack Developer', 
      course:'8 courses', 
      rating:'4.7 (567230)',
      pic:"https://www.gale.com/binaries/content/gallery/gale-us-en/banners/elearning/gale-presents-udemy-for-business/instructor-yu.jpg", 
    }, {
      id: 6, 
      name:"Pritam Ghosh", 
      info:'App Developer', 
      course:'21 courses', 
      rating:'4.7 (788945)',
      pic:"https://bgr.com/wp-content/uploads/2019/02/download-1.jpeg?resize=782", 
    }, {
      id: 7, 
      name:"Cristiano Ronaldo", 
      info:'Backend Developer', 
      course:'12 courses', 
      rating:'4.7 (905231)',
      pic:"https://thumbs.dreamstime.com/b/serious-thoughtful-young-indian-man-indoor-portrait-serious-thoughtful-young-indian-man-indoor-portrait-pensive-dreamy-handsome-280748083.jpg", 
    }, {
      id: 8, 
      name:"Leo Messi", 
      info:'Software Engineer', 
      course:'9 courses', 
      rating:'4.7 (127905)',
      pic:"https://st.depositphotos.com/1011643/4918/i/950/depositphotos_49181105-stock-photo-handsome-indian-man.jpg", 
    }, 
    {
      id: 9, 
      name:"Suman Gupta", 
      info:'Cloud Developer', 
      course:'15 courses', 
      rating:'3.9 (784346)',
      pic:"https://th.bing.com/th/id/R.35de0f4727193912ebaa245e3e8de111?rik=ZPJF8ATVLU%2bpNw&riu=http%3a%2f%2fdcvast.se%2fdev%2fwp-content%2fuploads%2f2019%2f08%2fheadshot2019-768x1152.jpg&ehk=92AzNjmwE2NskeKe7JDpbooM0foTANn5M%2frbufGNqqw%3d&risl=&pid=ImgRaw&r=0", 
    }, 
    {
      id: 10, 
      name:"Rohit Banerjee", 
      info:'Full Stack Developer', 
      course:'6 courses', 
      rating:'4.2 (905908)',
      pic:"https://th.bing.com/th/id/OIP.Tf5Wa8AayO8OlFNtwC8XkwAAAA?w=350&h=250&rs=1&pid=ImgDetMain", 
    }, 
    {
      id: 11, 
      name:"Karim shetty", 
      info:'Google cloud Developer', 
      course:'16 courses', 
      rating:'4.8 (345900)',
      pic:"https://i.kinja-img.com/image/upload/c_fit,q_60,w_645/78393d0ab5919d5ae345fc993134f913.jpg", 
    }, 
    {
      id: 12, 
      name:"Anis Biswas", 
      info:'Backend Developer', 
      course:'8 courses', 
      rating:'4.2 (785309)',
      pic:"https://th.bing.com/th/id/OIP.rFQyRuKghsBDKgQzpMdI0QHaE8?w=296&h=197&c=7&r=0&o=5&dpr=1.3&pid=1.7", 
    }, 
    {
      id: 13, 
      name:"Silpa Midda", 
      info:'UI/UX Designer', 
      course:'10 courses', 
      rating:'4.0 (567341)',
      pic:"https://cdn.mos.cms.futurecdn.net/THCiUmVZcgxHodGCK3EyYo-1200-80.jpg", 
    }, 
    {
      id: 14, 
      name:"Nandan Chatterjee", 
      info:'HTML Expert', 
      course:'5 courses', 
      rating:'4.9 (956734)',
      pic:"https://th.bing.com/th/id/OIP.A-blaFHsDiHn9C99f1FyYQHaHa?rs=1&pid=ImgDetMain", 
    }, 
    {
      id: 15, 
      name:"Sarat Kumar Sen", 
      info:'Google Cloud Developer', 
      course:'13 courses', 
      rating:'4.5 (685809)',
      pic:"https://th.bing.com/th/id/OIP.1QJyrTaB09VcWCu1NuefkAHaHa?w=180&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7", 
    }, 

] 
export default tutorsInfo;